### ISSUE TITLE
Experimental results under 1x(12ep) training strategy?

### ISSUE THREAD

**Issue by Jason-cpp** [hustvl/QueryInst#13]
Could you report the Experimental results of QueryInst under 1x training strategy?

**Comment by Yuxin-CV** [comment]
Hi, @Jason-cpp, thanks for your interest in our work!

`1x` schedule is originally designed for `Faster / Mask R-CNN` families, optimized using `SGD` with a learning rate `0.01`. 

While Transformer / Query based e2e object / instance level frameworks like `DETR`, `Def-DETR` & `Sparse R-CNN` are optimized via `Adam` families using a very small learning rate. Usually, it will take much longer for them to converge.

To my knowledge, under `1x` schedule, the ranking of `Box AP` is: `Faster / Mask R-CNN` >= `Sparse R-CNN` >= `Def DETR` >> `DETR`. If you are interested in the precise numbers, I suggest you open an issue in the corresponding repo.

Since the `1x` schedule cannot provide good enough detection performance, it is not so much meaningful to consider `1x` instance segmentation performance. 

Also, QueryInst is designed to be performance-oriented, _i.e._, we are not so much interested in the `1x` performance, but we do care about the fully converged model performance. 

We argue that `1x` is not a "standard schedule" for every model and it is too harsh to compare every model under the `1x` schedule (`1x` is too short), A good `1x` model is not guaranteed to be a good (fully converged) model, _e.g._, EfficientDets & YOLOS families all need hundreds of epoch to fully converge.

**Comment by Yuxin-CV** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions.
